[profile.default]
src = "contracts/src"
test = "contracts/test"
script = "."
out = "contracts/out"
libs = ["contracts/lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
hoodi = "${HOODI_RPC}"
sepolia = "${SEPOLIA_RPC}"
mainnet = "${MAINNET_RPC}"
base = "${BASE_RPC}"

[etherscan]
hoodi = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
